### ISSUE TITLE
It should be easy to start and stop MongoDB for tests

### ISSUE THREAD

**Issue by jochenberger** [sourcemuse/GradleMongoPlugin#17]
If a Gradle build contains tests that use MongoDB, it is quite cumbersome to start and stop MongoDB for their execution.
You could do something like
```
tasks.withType(Test).each {
  dependsOn(startMongoDb)
  finalizedBy(stopMongoDb)
}
```
But that will also start and stop MongoDB if the test task is skipped.
Currently I have resorted to something like
```
def mongoRunning = false

test {
  doFirst {
    startMongoDb.execute()
    mongoRunning = true
  }
  finalizedBy stopMongoDb
}

stopMongoDb{
  onlyIf {mongoRunning}
  doLast  {
    mongoRunning = false
  }
}
```
It would be nice if the plug-in supported that behavior out-of-the-box.

**Comment by roberttaylor426** [comment]
I'm not exactly sure what the issue is here. If the suggestions below miss the mark, could you please explain your use case a little more clearly?

'_If a Gradle build contains tests that use MongoDB, it is quite cumbersome to start and stop MongoDB for their execution._' - you're aware that the __startManagedMongoDb__ task will shutdown the Mongo instance for you, when the build completes? Or do you need to start and stop multiple Mongo instances during a build?

'_...that will also start and stop MongoDB if the test task is skipped._' - if the problem is that you don't always want Mongo to start up when particular test tasks are executed, perhaps you could create a separate test task altogether (IntegrationTest, FunctionalTest etc) and only have that depend on the _start(Managed)MongoDb_ task? Or if the problem is that you frequently skip the test task, perhaps you could [exclude it](https://gradle.org/docs/current/userguide/tutorial_gradle_command_line.html#sec:excluding_tasks_from_the_command_line) instead?

**Comment by jochenberger** [comment]
I know about the `startManagedMongoDb` task, but for a multi-project build, that starts one MongoDB instance after another and shuts them down when the whole project's build finishes. I could live with that but I'd rather like each subproject's instance to shut down when it isn't needed anymore.

> if the problem is that you don't always want Mongo to start up when particular test tasks are executed

No, I meant that the whole `test` Gradle task is not always executed, e.g. when the source files do not change between executions. Again, this is mostly relevant in multi-project builds.

**Comment by roberttaylor426** [comment]
Ah with you. I'll have a think about how this might work.

In the meantime do you have a sample project I could look at where you're trying to use the plugin in this way? Also do you have a proposal for how you'd ideally like to declare this kind of task-specific setup and teardown in your builds?

**Comment by jochenberger** [comment]
I'll start with the last question. I think I'd configure it on the mongo extension, maybe
```
mongo {
  startAndStopFor test
}
```
As to how this might work, I'm not sure. I guess you don't want to use the incubating `finalizedBy` feature, but I haven't found out how to add an `Action` to a `Task` that is executed no matter if the previous `Action`s succeeded or not. Maybe it could be done with a `TaskExecutionListener` (https://gradle.org/docs/current/javadoc/org/gradle/api/execution/TaskExecutionListener.html), but I haven't had the chance to look into that yet.
Unfortunately, I don't have a sample project ready at the moment, but maybe I'll find the time to put something together next week.

**Comment by jochenberger** [comment]
Yes, `TaskExecutionListener` looks promising: I added the following to my build script and it seems to do what I want:
```groovy
gradle.taskGraph.addTaskExecutionListener(
    [beforeExecute:{ final Task task->
        if (Test.isInstance(task)){
          startMongoDb.execute()
        }
      },
      afterExecute: { final Task task, final TaskState state->
        if (Test.isInstance(task)){
          stopMongoDb.execute()
        }
      }
    ] as TaskExecutionListener
)
```

**Comment by jochenberger** [comment]
Nope, I was wrong, the `beforeExecute` is also executed if the test task is up-to-date and will not run.

**Comment by roberttaylor426** [comment]
I've had a stab at spiking a solution for this. The changes have been included in the latest [0.6.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/sourcemuse/gradle/plugin/gradle-mongo-plugin/). Code is [here](https://github.com/sourcemuse/GradleMongoPlugin/compare/task_with_mongo_db_running). I also created a small [test project](https://github.com/roberttaylor426/gradle-mongo-plugin-test) to demonstrate the functionality.

I'm not so keen on having the Mongo configuration depend on the tasks themselves - it feels like the task configuration in question is the right place to declare such a dependency. With that in mind, the latest snapshot supports the following:

```
test {
    withMongoDbRunning()
   ...
}
```

It would be straightforward to permit a configuration block here as well.

What are your thoughts? Does this achieve what you're after?

**Comment by jochenberger** [comment]
Yes, that looks pretty good to me. I just gave the SNAPSHOT a shot and it works fine, thanks.
One minor issue: I'm not sure if it's possible, but what about allowing to configure the MongoDB instance within the `withMongoDbRunning` closure?
```
test {
    withMongoDbRunning {
      port 12345
    }
   ...
}
```
I guess, you'd have to create the extension on the `withMongoDbClosure` closure, right?

**Comment by roberttaylor426** [comment]
Yes, actually that's what I meant by my comment above - configuration for the Mongo instance could (should?) go here. This would allow for more flexible build configurations. 

It's quite conceivable that multiple tasks might need a running Mongo instance, each configured differently, especially in multi-project (potentially parallelized) builds. The best approach might well be a hybrid one, with both common and task-specific configuration options available.

**Comment by jochenberger** [comment]
I'm not sure about the project-level extension. Personally, I'd like
```
startMongoDb {
  port 12345
}
```
better than
```
mongo {
  port 12345
}
```
Also it looks more symmetric if we also have
```
test {
    withMongoDbRunning {
      port 12345
    }
   ...
}

```
Also, if you refactored StartMongoDB into a Task class, it would allow for things like
```
task startSecondaryMongoDB(type:StartMongoDB) {
  port 12346
}
```
But that's all just a matter of taste of course.

**Comment by roberttaylor426** [comment]
If we allow tasks to declare that they require mongo db to be running in the form proposed:
```
test {
    withMongoDbRunning {
        port 12345
    }
}
```
...do we still need the existing _start_/_stop_/_startManaged_ tasks? I've been wondering this since your original suggestion.

Why would we still need tasks to explicitly start and stop the database? What additional use cases do they cater for?

I've found 4 usages of the plugin on GitHub, all are simply using the `task.dependsOn startManagedMongoDb` approach. The new proposal seems superior, and it would simplify things if we could standardize plugin usage. Can you think of a use case the new approach doesn't support?

**Comment by jochenberger** [comment]
Well, I can't think of any, but that doesn't mean there is none. Besides, it always makes me so sad if existing functionality is removed. ;-)
Maybe it would be a good compromise to create dedicated classes for those tasks, "deprecate" the pre-configured tasks that are currently added by the plugin and remove them in a later release. If the task classes are still there, it'll be easy for people to add them back if they really need them.

**Comment by roberttaylor426** [comment]
Yeah, but [perfection is achieved not when there is nothing more to add, but when there is nothing left to take away](http://www.quotationspage.com/quote/26979.html). ;-)

I think your suggestions are sensible. We'll take this approach.

**Comment by roberttaylor426** [comment]
Apologies for the delay in getting this functionality out. I was having an unforeseen problem with Gradle when initially trying to implement it, and have since been very busy so have been unable to return to it. 

I hope to revisit the issue next week. Alternatively in the meantime feel free to raise a pull request ;-)

**Comment by jochenberger** [comment]
No worries, I have a workaround. I can try to create a PR, but that's also going to have to wait until next week at least. Currently, I'm quite busy myself.

**Comment by sfitts** [comment]
I'm assuming this hasn't made it into a release yet, correct?

FWIW, we're currently using the `task.dependsOn startManagedMongoDb` approach and I agree that it would be easier/better to declare the dependency like this.

**Comment by roberttaylor426** [comment]
No this feature hasn't made it into a release yet. I was having an issue on the branch I was working on and then started a new job so things got held up a little. 

I will take another look this evening and then at the very least push what I have.

Just to be clear @sfitts, you would prefer to be able to declare a dependency in the form described above? i.e.

```
test {
    withMongoDbRunning {
        port 12345
    }
}
```

**Comment by sfitts** [comment]
Yes, that approach seems reasonable, but just to make sure it won't break what we do here's more detail.  Currently we have a gradle script which we include in any project which requires mongo for its tests.  That script looks like this:

```
import com.mongodb.MongoClient

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.mongodb:mongo-java-driver:2.12.2"
    }
}

static boolean mongoInstanceRunning() {
    try {
        MongoClient mongoClient = new MongoClient()
        mongoClient.getDB('test').getStats()
    } catch (Exception e) {
        return false
    }
    true
}

apply plugin: 'mongo'

// Start the embedded Mongo DB if we don't have one running
startManagedMongoDb.onlyIf { !mongoInstanceRunning() }

// We want to start Mongo prior to running the tests
tasks.test.dependsOn('startManagedMongoDb')
```

If I understand correctly this would change to:

```
apply plugin: 'mongo'

test {
  withMongoDbRunning
}
```

This assumes that the declaration will start Mongo if it needs to and no-op if it doesn't (otherwise we'd have to continue to use our current approach).

**Comment by roberttaylor426** [comment]
Why would Mongo already be running in your case?

**Comment by sfitts** [comment]
There are times when we are debugging tests that it is convenient to control the start/stop of mongo directly.  So if the developer has started their own we simply defer to using it.  And no worries if you don't want to support that directly, we can just keep using our existing approach (which works fine).

**Comment by roberttaylor426** [comment]
I see.

Just out of curiosity, are you using the _start/stopMongoDb_ tasks provided by the plugin to do that?

**Comment by sfitts** [comment]
Not typically -- mostly it is just starting and stopping by hand in that case.

**Comment by roberttaylor426** [comment]
Understood, thanks.

**Comment by jochenberger** [comment]
What about merging the branch into master and creating a 0.9.0-beta-1 release? :-)

**Comment by roberttaylor426** [comment]
Alright I've spent some time revisiting this issue today (better late than never, I guess). 

First a short recap. As described above I originally wanted to support something like the following configuration:

```groovy
test {
    withMongoDbRunning {
        port 12345
    }
}
```
...where configuration at the task level overrode configuration at the project level.

The problem with my original spike was that I couldn't find a way to support overridding mongo configuration at the task level using that particular approach.

By adding a closure as an extension to the task I was able to support

```groovy
test {
    withMongoDbRunning()
}
```
but thanks to Gradle Magic<sup>TM</sup> things started breaking when a configuration block was passed in. Furthermore I think it's a little confusing for the user to have to execute a function within a configuration block. Indeed @sfitts (quite understandably) assumed above that

```groovy
test {
  withMongoDbRunning
}
```

would work, but it wouldn't.

So, I've come up with a revised approach:

```groovy
test {
  requiresMongoDb = true
}
```

Task-specific mongo configuration would be added like so:

```groovy
test {
  requiresMongoDb = true
  mongo {
  	port = 'random'
  }
}
```

This functionality is available in the latest 0.9.0-SNAPSHOT release, and my original test project has been updated to demonstrate its usage (see [here](https://github.com/roberttaylor426/gradle-mongo-plugin-test/blob/master/build.gradle)). PR with the proposed changes is [here](https://github.com/sourcemuse/GradleMongoPlugin/pull/34).

I realise that this approach is slightly more verbose than the original proposal but at the same time it feels more declarative and Gradle-idiomatic. Thoughts?

**Comment by sfitts** [comment]
This makes sense to me and I agree that it feels more "Gradle-ish".

**Comment by roberttaylor426** [comment]
Thanks @sfitts. (I've just enhanced the PR so that an existing mongo instance will be reused if available; new snapshot version published to the snapshots repository).

**Comment by jochenberger** [comment]
I don't care much about the exact syntax (method invocation, property or whatever), everything is probably simpler than what I do now.
But I'm not sure if I like the name of the `requiresMongoDb` property. Do we need that at all? Isn't it sufficient to check if the mongo extension is properly filled?

**Comment by jochenberger** [comment]
Apart from that, I just switched to the SNAPSHOT version and it seems to work fine.

**Comment by roberttaylor426** [comment]
Thanks for the feedback. I wish it were possible to do-away with the `requiresMongoDb` property, however I can't see a way around it. 

If a configuration block is passed in then sure, it's quite possible to detect that and respond accordingly. However what if a user wants to reuse the default or project-wide configuration?

```groovy
test {
    mongo
}
```

...where mongo (or whatever you want to name it) is an [extension object](https://docs.gradle.org/current/userguide/custom_plugins.html#N145D0) registered on the task won't work. Gradle doesn't even pass in a null value, so I have no way to detect that the user tried to 'invoke' the extension object. Hence the boolean `requiresMongoDb` property.

Now in the interests of brevity we _could_ permit the omission of the property if you're explicitly setting task-specific mongo configuration. So
```groovy
test {
    mongo {
        port = 'random'
    }
}
```
could be made to work. However now we're providing an inconsistent api, which voids any gain IMO.

If you know a clever implementation trick that means we can lose the property, I'm all ears. Otherwise I suggest we go with this for now.

**Comment by roberttaylor426** [comment]
(Apologies for getting the SNAPSHOT version wrong, btw. It should have of course been 0.10.0-SNAPSHOT).

**Comment by jochenberger** [comment]
Yes, the issue with the default configuration came to my mind later. However one could argue that the property should default to `true` on a `tasks.withType(Test)` since the user applied the plugin in the first place.

**Comment by roberttaylor426** [comment]
I'm not sure I'd agree with that argument. 

Consider the [testing pyramid](http://googletesting.blogspot.co.uk/2015/04/just-say-no-to-more-end-to-end-tests.html). Even if my system happens to integrate with MongoDb a _majority_ of my tests will likely want to run independently of any persistence mechanism (unless I'm writing a pure CRUD application). I've worked on a number of projects where we divided up our testing tasks so that unit tests (which don't depend on the database) can run as fast as possible; integration or system tests typically run as part of a separate suite. Defaulting to 'on' would therefore seem a bit presumptuous IMO.

Furthermore I like having some form of explicit dependency declaration. Having an implicit rule that states 'test' tasks will automatically spin up a mongo instance in the background would not be obvious to readers of the build scripts.

**Comment by jochenberger** [comment]
True. What about moving the property into the extension?
```
test {
  mongo {
    enable = true // or some better property name, "enable" is still not perfect
    port = 'random'
  }
}
```

**Comment by roberttaylor426** [comment]
Sure we could go that route, but then is there any real difference between that and the original proposal?

The only minor downside I can see is that by including the trigger property inside the mongo configuration we'd need to have different rules for configuration blocks specified at the project level and the task level. Project-level mongo configuration blocks wouldn't have any need for an `enable` option, and it might confuse some users.

**Comment by jochenberger** [comment]
> Sure we could go that route, but then is there any real difference between that and the original proposal?

First of all, it looks better, everything is nicely aligned and symmetric. ;-)
Then, I somehow down't like the "requiresMongoDb" name. I know it's a minor nitpick, but the name does not exactly represent what it does. I can set it to true if the test does not actually *reqire* MongoDB. Maybe you could change it to something like "runWithMongoDB"?

**Comment by roberttaylor426** [comment]
Sure, I'm happy to change `requiresMongoDb` to `runWithMongoDb`.

**Comment by roberttaylor426** [comment]
PR updated.

**Comment by roberttaylor426** [comment]
If there are no further suggestions by the end of the day I'll merge this to master and cut a new release.

**Comment by roberttaylor426** [comment]
0.10.0 released on central.
