### ISSUE TITLE
How to Increase Mongod Verbosity

### ISSUE THREAD

**Issue by phasebash** [sourcemuse/GradleMongoPlugin#21]
Is it possible to increase the verbosity of the logs from mongod?  If not, could we please add an option in the plugin extension to do so?

**Comment by roberttaylor426** [comment]
No, it's not currently possible to configure the verbosity of the mongod process.

How would a `mongodVerbosity` configuration option sound? I just raised a [pull request](https://github.com/sourcemuse/GradleMongoPlugin/pull/24) to provide such functionality. Would you mind taking a look and telling me if it suits your needs?

**Comment by roberttaylor426** [comment]
This change went into the 0.7.0 release. Let me know if you need anything added.

**Comment by phasebash** [comment]
Just curious why the MongoCmdOptionsBuilder used in GradleMongoPlugin wasn't called to set verbosity, why did we walk around the API that is already being used?

See: 
https://github.com/sourcemuse/GradleMongoPlugin/blob/master/src/main/groovy/com/sourcemuse/gradle/plugin/flapdoodle/gradle/GradleMongoPlugin.groovy
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/f95b98a98c8768eca6bbcd2ed4edeb07b934067f/src/main/java/de/flapdoodle/embed/mongo/config/MongoCmdOptionsBuilder.java

**Comment by roberttaylor426** [comment]
The mongod process allows for [multiple verbosity levels](http://docs.mongodb.org/manual/reference/program/mongod/#cmdoption--verbose) by repeating the `v` option. Via `MongoCmdOptionsBuilder` Flapdoodle only allows for the [first level of verbosity to be set](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java#L160). This may have been sufficient for your needs, but since it was relatively straightforward to implement I thought I'd go ahead and support the full range of verbosity levels.

**Comment by phasebash** [comment]
Fair point!
